# Generated by Django 4.2.16 on 2024-12-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lulaby",
        ),
    ]
