# Generated by Django 4.2.16 on 2024-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_delete_lulaby"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hadipa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aiyoo", models.CharField(max_length=100)),
            ],
        ),
    ]
