# Generated by Django 4.2.16 on 2024-12-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_collection_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orderitems",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="store.collection",
            ),
        ),
    ]
